services:

  db:
    image: postgis/postgis:17-3.5
    restart: unless-stopped
    # set shared memory limit when using docker compose
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: estate

  adminer:
    image: adminer
    ports:
      - 8080:8080